# Generated by Django 5.2.4 on 2025-07-03 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='catogory_name',
            new_name='category_name',
        ),
    ]
